[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
dynamic_padding = true
decorations = "None"
option_as_alt = "Both"

[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
bold_italic = { family = "CaskaydiaMono Nerd Font" }
size = 15

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[general]
import = ["~/.config/alacritty/themes/aura.toml"]
